AlBasedRecruiter/AlBasedRecruiter/Controllers/ApplicantController.cs
using AlBasedRecruiter.Models;
using Microsoft.AspNetCore.Mvc;
using NHibernate;

using NHibernate.Linq;

namespace AlBasedRecruiter.Controllers
{
    public class ApplicantController : Controller
    {

   

        [HttpGet]
        public IActionResult Index()
        {
            using (var session = NhibernateHelper.GetSession())
            {
                var applicants = session.Query<Applicant>()
                                    .Fetch(x => x.Recruiter)   // Assuming `Recruiter` is a navigation property
                                    .Fetch(x => x.JobPosition) // Assuming `JobPosition` is a navigation property
                                    .ToList();


                return View(applicants);
            }
        }
    }
}

AlBasedRecruiter/AlBasedRecruiter/Controllers/BiasController.cs
using AlBasedRecruiter.Models;
using Microsoft.AspNetCore.Mvc;
using NHibernate.Linq;

namespace AlBasedRecruiter.Controllers
{
    public class BiasController : Controller
    {
        public IActionResult BiasIndex()
        {
            using (var session = NhibernateHelper.GetSession())
            {
                var applicants = session.Query<Bias>()
                                    .Fetch(x => x.Interview)   // Assuming `Recruiter` is a navigation property
                                    .Fetch(x => x.JobPosition)
                                    .Fetch(x => x.Applicant)
                                    .Fetch(x => x.AIEvaluation)
                                     .Take(10)
                                    .ToList();


                return View(applicants);
            }
        }
    }
}

AlBasedRecruiter/AlBasedRecruiter/Controllers/HiringController.cs
using AlBasedRecruiter.Models;
using Microsoft.AspNetCore.Mvc;
using NHibernate.Linq;

namespace AlBasedRecruiter.Controllers
{
    public class HiringController : Controller
    {
        public IActionResult Result()
        {
            using (var session = NhibernateHelper.GetSession())
            {
                var applicants = session.Query<HiringOffer>()
                                    .Fetch(x => x.Interview)   // Assuming `Recruiter` is a navigation property
                                    .Fetch(x => x.JobPosition)
                                    .Fetch(x => x.Applicant)
                                    .Fetch(x => x.AIEvaluation)
                                     .Take(10)
                                    .ToList();


                return View(applicants);
            }
        }
    }
}

AlBasedRecruiter/AlBasedRecruiter/Controllers/InterviewController.cs
using AlBasedRecruiter.Models;
using Microsoft.AspNetCore.Mvc;
using NHibernate.Linq;

namespace AlBasedRecruiter.Controllers
{
    public class InterviewController : Controller
    {
        public IActionResult InterviewIndex()
        {
            using (var session = NhibernateHelper.GetSession())
            {
                var applicants = session.Query<Interview>()
                                        .Fetch(x => x.Recruiter)
                                        .Fetch(x => x.Applicant)
                                        .Fetch(x => x.JobPosition)
                                        .Take(10)
                                        .ToList();

                return View(applicants);
            }
        }
    }
}

AlBasedRecruiter/AlBasedRecruiter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlBasedRecruiter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AlBasedRecruiter.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AlBasedRecruiter</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="JobPosition" asp-action="Index">JobPosition</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Recruiter" asp-action="Index">Recruiter</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Applicant" asp-action="Index">Applicant</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Interview" asp-action="InterviewIndex">Interview</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="AIEvaluation" asp-action="AI">AIEvaluation</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Bias" asp-action="BiasIndex">Bias</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Hiring" asp-action="Result">Result </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AlBasedRecruiter - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>